apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: victorialogs
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: "trace_id:=\"$${__trace.traceId}\""

  - name: VictoriaLogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    editable: true
    jsonData:
      logLevelRules:
        - field: severity_text
          operator: equals
          value: ERROR
          level: error
          enabled: true
        - field: severity_text
          operator: equals
          value: WARN
          level: warning
          enabled: true
        - field: severity_text
          operator: equals
          value: WARNING
          level: warning
          enabled: true
        - field: severity_text
          operator: equals
          value: INFO
          level: info
          enabled: true
        - field: severity_text
          operator: equals
          value: DEBUG
          level: debug
          enabled: true
      derivedFields:
        - name: trace_id
          matcherType: label
          matcherRegex: trace_id
          datasourceUid: tempo
          url: "$${__value.raw}"
          urlDisplayLabel: 查看 trace
